default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET

default_test:
    path: /test
    defaults: { _controller: "AppBundle:Default:test" }
    methods: GET
